import Head from "next/head";
import {
  Button,
  Container,
  Grid,
  Stack,
  ThemeIcon,
  Title,
  Text,
  useMantineTheme,
  Center,
} from "@mantine/core";
import { EntityTable } from "root/components/EntityTable";
import { BookMetadata } from "root/models/Book";
import { IconChevronLeft, IconClipboardText } from "@tabler/icons-react";
import Link from "next/link";
import { useState } from "react";
import { BookCoverForm } from "root/components/BookCoverForm";

export default function BookAccounting() {
  const theme = useMantineTheme();
  const [selected, setSelected] = useState<number | undefined>(undefined);
  return (
    <>
      <Head>
        <title>Облік книг</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size="xl" my="xl" p={0}>
        <Grid>
          <Grid.Col span={12}>
            <Center>
              <Link href="/accounting">
                <Button variant="subtle" pl="xs" pr="lg">
                  <IconChevronLeft />
                  Назад
                </Button>
              </Link>
            </Center>
          </Grid.Col>
          <Grid.Col span={12}>
            <Stack align="center">
              <Title align="center">
                <ThemeIcon size={34} variant="default" radius="md">
                  <IconClipboardText color={theme.fn.primaryColor()} />
                </ThemeIcon>
                &nbsp;&nbsp;Книга
              </Title>
              <Text align="center">
                Список описів видань та створення згадки про них у системі
              </Text>
            </Stack>
          </Grid.Col>

          <Grid.Col lg={9} md={12}>
            <EntityTable
              metadata={BookMetadata}
              untitled={true}
              controlled={undefined}
              singular={{ val: selected, set: setSelected, mod: true }}
              crudEnabled={true}
            />
          </Grid.Col>
          <Grid.Col lg={3} md={12}>
            <BookCoverForm fromId={selected} />
          </Grid.Col>
        </Grid>
      </Container>
    </>
  );
}
