import Head from "next/head";
import { Container, Grid, rem, Title } from "@mantine/core";
import {
  IconReceipt,
  IconReceiptRefund,
  IconSquareRoundedPlus,
} from "@tabler/icons-react";
import { DBEntityButton } from "root/components/Buttons/DBEntityButton";
import { BookCategoryMetadata } from "root/models/BookCategory";
import { BookMetadata } from "root/models/Book";
import { BorrowMetadata } from "root/models/Borrow";
import { ReturnMetadata } from "root/models/Return";
import { SupplierMetadata } from "root/models/Supplier";
import { SupplyMetadata } from "root/models/Supply";

const HEIGHT_1 = rem(100);

export default function Accounting() {
  return (
    <>
      <Head>
        <title>Облік</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size="xl" my="xl" p={0}>
        <Grid>
          <Grid.Col span={12} my="xl">
            <Title order={1} align="center">
              Екран обліку
            </Title>
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={undefined}
              metadata={BookCategoryMetadata}
              height={HEIGHT_1}
              link="/accounting/bookcategory"
            />
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={undefined}
              metadata={BookMetadata}
              height={HEIGHT_1}
              link="/accounting/book"
            />
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={<IconReceipt size="2.375rem" />}
              metadata={BorrowMetadata}
              height={HEIGHT_1}
              link="/accounting/borrow"
            />
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={<IconReceiptRefund size="2.375rem" />}
              metadata={ReturnMetadata}
              height={HEIGHT_1}
              link="/accounting/return"
            />
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={undefined}
              metadata={SupplierMetadata}
              height={HEIGHT_1}
              link="/accounting/supplier"
            />
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={<IconSquareRoundedPlus size="2.375rem" />}
              metadata={SupplyMetadata}
              height={HEIGHT_1}
              link="/accounting/supply"
            />
          </Grid.Col>
        </Grid>
      </Container>
    </>
  );
}
