import Head from "next/head";
import {
  Button,
  Container,
  Grid,
  useMantineTheme,
  Text,
  Stack,
  ThemeIcon,
  Title,
  Center,
} from "@mantine/core";
import { EntityTable } from "root/components/EntityTable";
import { SupplierMetadata } from "root/models/Supplier";
import { IconChevronLeft, IconUserDown } from "@tabler/icons-react";
import Link from "next/link";

export default function SupplierAccounting() {
  const theme = useMantineTheme();
  return (
    <>
      <Head>
        <title>Постачальники</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size="xl" my="xl" p={0}>
        <Grid>
          <Grid.Col span={12}>
            <Center>
              <Link href="/accounting">
                <Button variant="subtle" pl="xs" pr="lg">
                  <IconChevronLeft />
                  Назад
                </Button>
              </Link>
            </Center>
          </Grid.Col>
          <Grid.Col span={12}>
            <Stack align="center">
              <Title align="center">
                <ThemeIcon size={34} variant="default" radius="md">
                  <IconUserDown color={theme.fn.primaryColor()} />
                </ThemeIcon>
                &nbsp;&nbsp;Постачальник
              </Title>
              <Text>Список постачальників та джерел надходження фонду</Text>
            </Stack>
          </Grid.Col>
          <Grid.Col span={12}>
            <EntityTable
              metadata={SupplierMetadata}
              untitled={true}
              controlled={undefined}
              singular={undefined}
              crudEnabled={true}
            />
          </Grid.Col>
        </Grid>
      </Container>
    </>
  );
}
