import Head from "next/head";
import { AuthContent } from "root/components/AuthContent";

export default function Register() {
  return (
    <>
      <Head>
        <title>Реєстрація</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthContent toggled="register" />
    </>
  );
}
